name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: latest }
          - { os: macos-latest, crystal: latest }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Cache shards
        uses: actions/cache@v5
        with:
          path: |
            lib
            bin/ameba*
          key: ${{ matrix.os }}-shards-${{ hashFiles('**/shard.lock') }}

      # ---- Build debug release and check code quality on all platforms

      - name: Install shards
        run: shards check || shards install

      - name: Run tests
        run: crystal spec

      # ---- format and lint check on Linux only

      - name: Check formatting (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: crystal tool format; git diff --exit-code src

      - name: Build ameba  (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: mkdir -p bin; cp lib/ameba/bin/ameba.cr bin && crystal build -Dpreview_mt -o bin/ameba bin/ameba.cr

      - name: Run static code analysis (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: bin/ameba src/
